version: '2'
services:

  prom:
    image: prom/prometheus:latest
    ports:
      - "82:9090"
    volumes:
      - ./prom/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - splunk

  splunk:
    image: splunk/splunk:8.0
    hostname: splunk
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_USER=root
      - SPLUNK_ENABLE_LISTEN=9997
      - SPLUNK_PASSWORD=password
    ports:
      - "80:8000"

  splunkforwarder:
    image: splunk/universalforwarder:8.0
    hostname: splunkforwarder
    environment:
      - SPLUNK_START_ARGS=--accept-license --answer-yes
      - SPLUNK_STANDALONE_URL=splunk:9997
      - SPLUNK_USER=root
      - SPLUNK_ADD=monitor /logs
      - SPLUNK_PASSWORD=password
    restart: always
    depends_on:
      - splunk
    volumes:
      - log_volume:/logs

  nodejs-srv:
    build: nodejs-srv
    depends_on:
      - splunkforwarder

  java-srv:
    build: java-srv
    ports:
      - "81:8080"
    user: root  # has to run as root user, because it needs to write logs to shared volume
    environment:
      - LOGGING_FILE_NAME=/logs/demo-application.log
    volumes:
      - log_volume:/logs
    depends_on:
      - nodejs-srv

volumes:
  log_volume:
